### ISSUE TITLE
Google Play rejection because of Unsafe Encryption in com.fleksy.services.library.a.j.a

### ISSUE THREAD

**Issue by artkat** [FleksySDK/VirtualKeyboardSDK#150]
### Discussed in https://github.com/FleksySDK/VirtualKeyboardSDK/discussions/149

<div type='discussions-op-text'>

<sup>Originally posted by **artkat** August  2, 2024</sup>
Preparing our app for launch on Google Play Console (Android) we encountered the following rejection reason: 
Your app contains unsafe cryptographic encryption patterns. Please see [this Google Help Center article](https://support.google.com/faqs/answer/9450925) for details.

com.fleksy.services.library.a.j.a

![image](https://github.com/user-attachments/assets/69946ad4-e616-43e6-9e79-9bb3d9516ebb)

Please advise how to proceed.</div>

**Comment by xevifar** [comment]
Hello @artkat , 

We are looking into it and we should have a fix during this week. 
cc @francescojalvo

**Comment by francescojalvo** [comment]
Hi @artkat we have prepared a new version of our SDK (v4.14.0) that should fix this issue. 

This issue was happening because we didn't update properly our SDK to support Android 5.

This new version also improves the look and feel of the keyboard and you will notice that the keys (by default) are shown in a more standard layout:

Before:

![image](https://github.com/user-attachments/assets/49bf5879-4831-467f-be54-ab16ba1a77c2)

Now (4.14.0)

![image](https://github.com/user-attachments/assets/818539ed-c28c-4400-8c85-0fa92379035b)

Let me know if it looks good on your side. 

PS: If you want to go back to the previous layout you should set the `useStandardLayoutSystem` configuration value ( to `false` (now the default is `true`) as documented [here](https://docs.fleksy.com/sdk-android/api-reference-android/keyboardconfiguration/#styleconfiguration)

**Comment by artkat** [comment]
Hi Xevi and Fransesco,

Thank you for the (as always) fast and adequate support.
Will test it in the coming week and let you know the results.

btw: I think the new layout is better ;-)

Regards,

Arthur Kater
PlazaLOGIC
